name: zeyan test expression
on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'this is input1'
        required: true
        type: choice
      input2:
        description: 'this is input2'
        required: true
        type: string
jobs:
  input1Job:
    runs-on: ubuntu-latest
    if: ${{ inputs.input1.length() > 0 }}
    steps:
    - name: input1Step
      if: ${{ inputs.input1 == '123' }}
      run: |
        echo "not skip for input1 is $inputs.input1"
    - name: input2Step
      if: ${{ inputs.input2 == 123 }}
      run: |
        echo "inputs.input2 is $inputs.input2"
  input2Job:
    runs-on: ubuntu-latest
    if: ${{ inputs.input2 == '123' }}
    steps:
    - name: input1Step
      if: ${{ inputs.input1 == '123' }}
      run: |
        echo "not skip for input1 is $inputs.input1"
    - name: input2Step
      if: ${{ inputs.input2 == 123 }}
      run: |
        echo "inputs.input2 is $inputs.input2"
